### ISSUE TITLE
After a value is typed into an input field then the value from the page state rendered is ignored

### ISSUE THREAD

**Issue by PhilAndrew** [fomkin/korolev#111]
In my use case I have a page with a form and a list of Customers. The form has a customer name.
When someone clicks on a customer in the list I populate the customer form like this from the state.

```
  def formFieldCustomer(title: String, elId: ElementId, name: String, value: String) = {
    'div('class /= "form-group",
      'label('class /= "col-sm-3 control-label", title),
      'div('class /= "col-sm-9",
        'div('class /= "input-group",
          'input(elId, 'name /= name, 'type /= "text", 'class /= "form-control", 'placeholder /= title, 'value /= value)
        )
      )
    )
  }
```

Now if the user clicks on a customer in the list, the value gets set in the input field from customer state and that's good. If the user clicks on another customer, the value gets set, that's good.

Now if the user types in the input field, then now clicks on a customer, the customer's value does not get set anymore, the value that was typed in the input field remains, even if I click on any customer in the list. This is a problem.

Previously as a solution I was doing:

`access.property[String](bankAccountNameField).set('value, item.accountName)`

But this is no good for 50 fields, its too slow.

I should also add that if I inspect the HTML DOM with Chrome inspector debugger I can see the CORRECT value is set in the HTML DOM but the value that I inputted by typing appears to still be there.

**Comment by PhilAndrew** [comment]
I worked out  a solution. I made all the form HTML disappear by changing state then have the form HTML re-appear by changing state again, all the form html is re-created, two state changes. At least this solution is acceptable for me for the moment.

**Comment by fomkin** [comment]
Hi! Do you try to use property operator `:=` instead of attribute operator `/=`? 

```
'input(elId, 
  'name /= name, 'type /= "text", 'class /= "form-control", 
  'placeholder /= title, 'value := value)
```

In nearest future I'll unify the operators and the problem will gone, but currently it's a solution.

**Comment by PhilAndrew** [comment]
What about a textarea, the value inside is not an attribute

**Comment by fomkin** [comment]
`:=` is a property-set-operator. It should work fine on text area, except static rendering case. 

```scala
'textarea('value := text,
  text // necessary if textarea shows in initial state
)

'input(
  'value := text,
  'value /= text // necessary if input shows in initial state
)
```

**Comment by PhilAndrew** [comment]
Under some condition (that I have not yet worked out), your suggested solution is not working and the old value remains in the text box.

**Comment by PhilAndrew** [comment]
If something is hidden, display: none, are you NOT sending the change down?

**Comment by fomkin** [comment]
Hmm. This is looking strange. Korolev does not tracks style properties in a some special way. Possible it is a bug in the changes-inferring algorithm. The algorithm used in 0.3.0 has not have comprehensive tests so problems like this is possible. Try to shuffle attributes, it can help in such cases. 

Currently I hard working under new template engine and changes-inferring algorithm (DSL will be compatible). https://github.com/fomkin/levsha It will be much faster (thousands of complex trees comparision per second), and will have very low memory-allocation rate. Also it has very strict property checks. I plan release at the end of May.

**Comment by PhilAndrew** [comment]
I only have the problem with 'value 's being set := AND only after a user has typed in the field AND only for some fields, not all fields, no time at the moment to find out why, so I revert to just removing and re-creating the form by changing state for the moment, I'll get back to trying to find the cause of the problem later.

**Comment by PhilAndrew** [comment]
The problem happens as follows for me now:
1. I set a value in the form and save my record. So I have typed in the input box.
2. I load a record which has a value of "" (empty string) then it doesn't overwrite the value in the input box.
3. I load a record with a value of "hello" and it does overwrite the value on the input box.

`<input value /= something, value := something ...`

When the value to be set is blank, a string of no length "". In this case the value is not updated.

**Comment by PhilAndrew** [comment]
I just cut down my HTML until it works and now expanding until I can find out when it doesn't work.

**Comment by fomkin** [comment]
I sure it is a bug in changes-inferrer.

**Comment by PhilAndrew** [comment]
Now I have everything in a working state but I still don't know what the problem was caused by, I'm just happy to be in a working state.

**Comment by fomkin** [comment]
Need to text it 0.4.0 release

**Comment by PhilAndrew** [comment]
This bug is in the 0.4.3 release for me for empty strings ""

**Comment by fomkin** [comment]
`access.resetForm` should help.
