### ISSUE TITLE
File upload of large files over a certain size fails

### ISSUE THREAD

**Issue by PhilAndrew** [fomkin/korolev#112]
My code based on this:

https://github.com/fomkin/korolev/blob/master/examples/form-data/src/main/scala/FormDataExample.scala

When uploading a file over a certain size it just stops the progress and stops uploading.

**Comment by PhilAndrew** [comment]
Can pay $100 USD for a fix if I can have it by Friday some time

**Comment by PhilAndrew** [comment]
Usually its because of multi-part form upload, you need multi-part for large file uploads.

http://stackoverflow.com/questions/4526273/what-does-enctype-multipart-form-data-mean

http://stackoverflow.com/questions/8659808/how-does-http-file-upload-work

**Comment by fomkin** [comment]
Korolev uses `mutipart/form-data` encoding. Please, tell me size of file. I'll try to reproduce it now.

**Comment by PhilAndrew** [comment]
Balsamiq_Mockups_3.5.9.exe downloaded from https://balsamiq.com/ uploads to Progress: 10.95988832833462% on my code base, I can't share the code I'm working on, but I assume the same problem will happen with yours

**Comment by fomkin** [comment]
Got it. I figured out what is  happening. The problem was in maximum request body limit hardcoded to 1M. Hot fix in progress.

**Comment by fomkin** [comment]
Hotfix will be available from Central in few hours.

> Can pay $100 USD for a fix if I can have it by Friday some time

Bug report is a payment :) This increases Korolev maturity.

**Comment by fomkin** [comment]
Limits now is configurable 

1. https://github.com/fomkin/korolev/blob/master/examples/form-data/src/main/scala/FormDataExample.scala#L12
2. https://github.com/fomkin/korolev/blob/master/examples/form-data/src/main/scala/FormDataExample.scala#L123

**Comment by PhilAndrew** [comment]
I keep my promises, if you wish to have the payment ask me for it, thanks! 

Also, it seems to use a lot more memory if I put that limit up to something like:

`class WebServer extends KorolevBlazeServer(BlazeServerConfig(maxRequestBodySize = 180 * 1024 * 1024)) {`
