### ISSUE TITLE
To show that web component does not load correctly when dynamically loaded 

### ISSUE THREAD

**Issue by PhilAndrew** [fomkin/korolev#115]
`sbt webComponentExample/run`

The web component for xMultiselect loads correctly on the initial page load but if you click the button "Click to load web component" you will notice the second one does not load correctly, it just displays a dropdown but without the initial selected value for the multi-select.

It does however seem to behave correctly as a web component once the dropdown is clicked.

I found the same problem with another web component, so I'm sure the problem is related to the loading.

The pull request is referenced here for the bug reproduction:
https://github.com/fomkin/korolev/pull/114

My web browser is Chrome.

**Comment by PhilAndrew** [comment]
Can you suggest a workaround even if its a hack, such as injecting html directly into there using attribute set.

**Comment by fomkin** [comment]
I have no idea :( Korolev doesn't have any specific code to support webcomponents. WebComponent (Custom Elements+ Shadow DOM) by design should behave as regular HTML tag. There is no difference between, for example, input or textarea, and any custom element. Dynamically appending is just chain of calls:

```javascript
var node = document.createElement('x-mutiselect')`
node.setAttribute(...)
node.setAttribute(...)
node.appendChild(...)
```

Maybe it is a bug in `x-multiselect`. I guess it just doesn't handle attributes updates in a child nodes. I'll investigate this problem on weekend.

**Comment by PhilAndrew** [comment]
Really appreciate you looking at it.

**Comment by PhilAndrew** [comment]
I believe this one had the same problem https://www.webcomponents.org/element/matthewp/searchable-multi

**Comment by fomkin** [comment]
My my assumption was right. Both of them doesn't track changes in the child nodes. It means they are not behave as a regular elements, and cannot be used with Korolev.

**Comment by fomkin** [comment]
So it means this is a bug in the components. You can fix them using https://developer.mozilla.org/en/docs/Web/API/MutationObserver

**Comment by PhilAndrew** [comment]
Great thanks, I can fix that bug in the component and allow the component to refresh more correctly.
