### ISSUE TITLE
When the server stops working the client stops working

### ISSUE THREAD

**Issue by PhilAndrew** [fomkin/korolev#116]
When the server stops working the client stops working, while that makes sense logically, but for the user this is not so nice.

For the user it would be good if the user is shown a screen indicating that the server is offline or the server is upgrading, please wait. For this I could make this myself by having a state change and showing a notification before I upgrade the server by taking it down.

For the user it would also be good if the user could have the page automatically refresh when the server comes back online again.

**Comment by fomkin** [comment]
> For the user it would be good if the user is shown a screen indicating that the server is offline or the server is upgrading, please wait. For this I could make this myself by having a state change and showing a notification before I upgrade the server by taking it down.

Good idea! Could you suggest convenient API?

> For the user it would also be good if the user could have the page automatically refresh when the server comes back online again.

There are two cases.
1. Reconnecting after network error or disconnecting. It works and if you use some in-memory cache. This should cover your need.
2. Refreshing page after a server restart with losing a state. The functionality is envisaged but currently is disabled. In the real-world cases it's useless, and suitable only for reducing WTF when development.

**Comment by fomkin** [comment]
#121 and #128 solve the problems
