### ISSUE TITLE
Need to scroll the browser view to a position when the user clicked on a link from Korolev

### ISSUE THREAD

**Issue by PhilAndrew** [fomkin/korolev#117]
Well, normally I would make a HTML anchor

<a name="raptors" />

Then use <a href="#raptors" ...

However I wish to have a Korolev event happen when the users clicks so this is a problem once we are in the Korolev event we can't go to #raptors, what to do? Basically want to scroll the UI to the element

**Comment by fomkin** [comment]
Workaround
```scala
access.evalJs(js"$element.scrollIntoView()")
```
