### ISSUE TITLE
Writing components is difficult due to them being dependent on global state

### ISSUE THREAD

**Issue by PhilAndrew** [fomkin/korolev#118]
I've been attempting to write a component which can be used on different pages and moved from one Korolev project to another, the problem is that state transitions must occur on the global state (I believe). I'm always returning a global state whenever I do a state change.
Why is that a problem? A UI component shouldn't know about the global state, it should be portable between Korolev projects.

For example I wrote a Korolev component and then it works in my sample project with its own state then I want to put it into a new State case class wrapper, then its difficult to add it to the wrapper class.

I feel the problem is that we are always returning a global state for transition and immediateTransition, not a local state.

Or is this a misunderstanding by me.

**Comment by fomkin** [comment]
> Writing components is difficult

It's not a bug -- it's a feature :) Usually when we say "components" we mean an UI element with an own state. Korolev doesn't support components by it's design, cause it leads to multi-state and breaks the simplicity which we want to reach. However you still could use WebCompoents (in the future you will able to crete WebComponents using Scala.js and Korolev's DSL). Also you can share UI structure (but not behavior) between your projects.

```scala
// In the shared module
class MyCompoents[F[+_]: Async, S, M](effects: Effects[F, S, M]) {
  import effects._
  def IconButton(icon: String, label: String)(event: Event) = {
    'div('class /= "icon-button",
      'img('class /= "icon-button_icon", 'src /= icon),
      'span('class /= "icon-button_label", label),
      event
    )
  }
}

// In the project
val mc = new MyCompoents(MyState.effects)
...
mc.IconButton("icons/fire.png", "Click Me") {
  event('click) {
    ...
  }
}
```

**Comment by fomkin** [comment]
I change my mind. Stateful components are really necessary. Goodbye, simplicity. Hello multiple state :( See https://github.com/fomkin/korolev/issues/162

**Comment by PhilAndrew** [comment]
Thanks. Currently when I do components what I usually do is that I make a render method which takes one or more callbacks when state changes. Then the user of the method implements the callbacks.

Eg.

```
  type ChangeCallback = (State, LocalDate, Boolean) => State
  type StateToDateCallback = (State) => LocalDate

  def calendarComponent(state: State, stateToDateCallback: StateToDateCallback, changeCallback: ChangeCallback) = {

```
