### ISSUE TITLE
invoke an event in korolev programmatically

### ISSUE THREAD

**Issue by ferrlin** [fomkin/korolev#119]
How to invoke an event programmatically? 

This is for the purpose of bypassing user generated event and straight to calling the event handler when an event is made.

Thanks in advance.

**Comment by fomkin** [comment]
No, its impossible. Would you describe your case in details?

**Comment by ferrlin** [comment]
I defined an event handler that is used inside an event#transition block. i want to use this the same handler but in the absence of an event generated by the user rather will be called when a change in state happens.

**Comment by fomkin** [comment]
Maybe you need dealy? https://github.com/fomkin/korolev/blob/master/examples/delay/src/main/scala/DelayExample.scala

**Comment by ferrlin** [comment]
Thanks for the suggestion.

I'll try some other ways to do this.
