### ISSUE TITLE
Edge servers

### ISSUE THREAD

**Issue by PhilAndrew** [fomkin/korolev#125]
I am thinking how to have edge servers for Korolev. We have customers in different region's of the world. Any thoughts on this?

**Comment by fomkin** [comment]
Can you explain a details? Is it a topic about cross datacenter usage that we have discussed before in Gitter?
![Cross DC Korolev](https://files.gitter.im/fomkin/korolev/Oe8d/korolev-geo-distributed.png)

**Comment by fomkin** [comment]
Does it help?
