### ISSUE TITLE
Text input sends click events to WebSocket event though there is no listener

### ISSUE THREAD

**Issue by Tvaroh** [fomkin/korolev#139]
Check `FocusExample` in examples to reproduce - just do `Bridge.setProtocolDebugEnabled(true)` and click on text input.

**Comment by fomkin** [comment]
Oh, I see. It is normal behaviour. Client doesn't listen concrete node in a DOM. Instead of this it listen all events of the one type on a `document` and send them to server. Server decide what to do with the event by himself.
