### ISSUE TITLE
Do you have any notes on how to upgrade from 0.3.x to 0.4.x ?

### ISSUE THREAD

**Issue by PhilAndrew** [fomkin/korolev#143]
I tried to upgrade the SBT version but this was a problem, some errors around in code.

**Comment by fomkin** [comment]
Of course. https://github.com/fomkin/korolev/releases/tag/v0.4.0 see migratin guide paragraph.

**Comment by fomkin** [comment]
@PhilAndrew Does it help?

**Comment by PhilAndrew** [comment]
Taking a look now.

**Comment by PhilAndrew** [comment]
Yes thanks, one change which is slightly annoying is that before I could pass
elem: ElementID as parameters to method now I got to do a bigger ElementID with 3 type parameters

**Comment by fomkin** [comment]
Alias for ElementId can be imported from applicationContext.
