### ISSUE TITLE
Strange behavior of the diff algorithm

### ISSUE THREAD

**Issue by lolgab** [fomkin/korolev#147]
I was working on a table when I encountered a strange behavior of Korolev updating the Dom.
I want to change an attribute of a node but it is changed on the parent node instead.
Clone this repository and run it.
Click on the arrow ordering button of the table at the right and look how the dom changes. I change the 'i class attribute at line 76 but the change is applied on parent 'div node.
[https://github.com/lolgab/KorolevDiffTable](GitHub repo with my code)

**Comment by fomkin** [comment]
Looks like it is the same https://github.com/fomkin/korolev/issues/108

**Comment by PhilAndrew** [comment]
What is the cause of the problem in this case, is it the i tag?

**Comment by PhilAndrew** [comment]
Solution for this bug is to get the HTML of the table header more correct.

Change renderTable to:
```
  def renderTable(state: State): Node = {
    'table (
      'class /= "table table-bordered",
      'thead (
        'tr (
          'th(
          'div (
            icon(state.tableState.tableOrdering.o1),
            tableTitles
          )
          )
        )
      ),
      'tbody (
        for (row <- state.tableState.table)
          yield
            'tr (
              'td (row.c1)
            )
      )
    )
  }
```
