### ISSUE TITLE
How to run examples?

### ISSUE THREAD

**Issue by PhilAndrew** [fomkin/korolev#160]
How can I run the Korolev demos now?
If I just run the main class from IntelliJ it doesn't work correctly
it fails to load the javascript library for Korolev
The javascript come back like <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html><head><script language="javascript">window['KorolevConfig'] = {
'sessionId': 'LJIIaAYh94CreMoB',
_

**Comment by fomkin** [comment]
Starting from Korolev 0.5, client side compiles using Google Closure Compiler. It's SBT step, IntelliJ just ignores it. You should run examples from SBT.
