### ISSUE TITLE
Korolev does not work when combined with webcomponents.js polyfill in Internet Explorer

### ISSUE THREAD

**Issue by PhilAndrew** [fomkin/korolev#161]
To use this web component in Internet Explorer I must include the web-component polyfill. Many web components require polyfill to work in IE. Note this problem only happens on IE.

https://github.com/tabalinas/multiselect-web-component

The problem is that now if I include this line

        'script('src /= "https://tabalinas.github.io/multiselect-web-component/webcomponentsjs/webcomponents.js")

Then Korolev does not work.

The following example shows the web component working in Internet Exploerer but the button "Sign In" does not work when webcomponents.js is included, if I remove webcomponents.js then Korolev works but the web component no longer worked in IE.

```
import korolev._
import korolev.blazeServer._
import korolev.execution._
import korolev.server.{KorolevServiceConfig, ServerRouter, StateStorage}
import levsha.events.EventPhase

import scala.concurrent.Future

object WebComponentExample extends KorolevBlazeServer {

  import State.applicationContext._
  import symbolDsl._

  def setLatLon(lat: Double, lon: Double) =
    immediateTransition { case s =>
      s.copy(lat = lat, lon = lon)
    }

  val service = blazeService[Future, State, Any] from KorolevServiceConfig [Future, State, Any] (
    serverRouter = ServerRouter.empty[Future, State],
    stateStorage = StateStorage.default(State()),
    head = {
      Seq(
        'link('rel /= "import", 'href /= "https://tabalinas.github.io/multiselect-web-component/component/multiselect.html"),
        'script('src /= "https://tabalinas.github.io/multiselect-web-component/webcomponentsjs/webcomponents.js")
        //'link('rel /= "import", 'href /= "https://leaflet-extras.github.io/leaflet-map/bower_components/leaflet-map/leaflet-map.html")
      )
    },
    render = {
      case state =>
        'body (
          'div (
            'button(event('click, EventPhase.AtTarget) {
              println("CLICK")
              immediateTransition { case s => s }
            }, "Sign in"),
            'button ("San Francisco", event('click)(setLatLon(37.7576793, -122.5076402))),
            'button ("London", event('click)(setLatLon(51.528308, -0.3817983))),
            'button ("New York", event('click)(setLatLon(40.705311, -74.2581908))),
            'button ("Moscow", event('click)(setLatLon(55.748517, 37.0720941))),
            'button ("Korolev", event('click)(setLatLon(55.9226846, 37.7961706)))
          ),
          'leafletMap (
            'style /= "width: 500px; height: 300px",
            'latitude /= state.lat.toString,
            'longitude /= state.lon.toString,
            'zoom /= "10"
          ),
          'xMultiselect(
            'placeholder /= "Select Value",
            'li(
              'value /= "1",
              'selected /= "",
              "Argentina"
            ),
            'li(
              'value /= "2",
              "Australia"
            ),
            'li(
              'value /= "3",
              "Brazil"
            ),
            'li(
              'value /= "4",
              "Canada"
            ),
            'li(
              'value /= "5",
              'selected /= "",
              "China"
            ),
            'li(
              'value /= "6",
              "France"
            ),
            'li(
              'value /= "7",
              "Germany"
            ),
            'li(
              'value /= "8",
              'selected /= "",
              "India"
            ),
            'li(
              'value /= "9",
              "Mexico"
            ),
            'li(
              'value /= "10",
              "Russia"
            ),
            'li(
              'value /= "11",
              'selected /= "",
              "United States"
            )
          )
        )
    }
  )

}

case class State(lon: Double = 0, lat: Double = 0)

object State {
  val applicationContext = ApplicationContext[Future, State, Any]
}

```

**Comment by fomkin** [comment]
1. Looks like this polyfill recreating whole DOM on start, so Korolev losing control. Lack of implicit DOM manipulation is strong requirement for Korolev.
2. The polyfill, you are use, is obsolete and implements old version of Web Components API. Better to use latest one. It works fine https://cdnjs.com/libraries/webcomponentsjs
3. The `x-multiselect` is also obsolete, because use old CE API. I've made pull request with compatibility fix https://github.com/tabalinas/multiselect-web-component/pull/4

**Comment by PhilAndrew** [comment]
I tried again and bower install --save and then the dropdown doesn't drop down
the selected items show inside the dropdown box as selected items, but when I click the dropdown to drop down it doesn't drop down. Apart from that the click button works in IE and Chrome.
no javascript errors.

<content class="content style-scope x-multiselect" select="li"></content> doesn't contain any li's but it used to contain them for the older version of the component. For this new version of the component when I use chrome inspector I don't see the li's.

Am I importing it wrong?

```
   Seq(
    'script('src /= "multiselect-web-component/bower_components/webcomponentsjs/webcomponents-loader.js"),
    'link('rel /= "import", 'href /= "multiselect-web-component/src/multiselectnew.html")
  )

```

**Comment by fomkin** [comment]
1. `attachShadow` is a new Shadow DOM API, `createShadowRoot` is old. See https://www.w3.org/TR/shadow-dom/
2. You are use `webcomponents-loader.js`. I don't tested with this. It better to use `webcomponents-lite.js`. `x-multiselect` uses all polyfills: Custom Element, HTML Imports, and Shadow DOM

**Comment by PhilAndrew** [comment]
Tried but dropdown still doesn't work for me, does it work for you? If it works for you then I'm doing something wrong.

**Comment by PhilAndrew** [comment]
Internet explorer and web components are really not friends.

**Comment by fomkin** [comment]
I think `x-multi select` just does not tested well. Web standards is a hell, so if developer of component doesn't check compatibility, component will not work well on all browsers. I've made a lot of work to let Korolev work in different browsers.
