### ISSUE TITLE
Consider merging Router's static & dynamic branches into one

### ISSUE THREAD

**Issue by Tvaroh** [fomkin/korolev#202]

**Comment by fomkin** [comment]
Could you suggest new API?

**Comment by Tvaroh** [comment]
Need to think...

**Comment by fomkin** [comment]
Ok. My plan is:

1. Remove `ServerRouter`
2. `KorolevServiceConfig.router` will be `(DeviceId, Option[SessionId]) => Router[F, S, Option[S]]`. It meats that `sessionId` and current state (which is available only in dynamic mode) become optional.
3. Router initialization will be invoked twice with somes and without them
