### ISSUE TITLE
Dropdown select does not reset when return to view it

### ISSUE THREAD

**Issue by PhilAndrew** [fomkin/korolev#204]
When I create a select

    'select( .... 
          for (c <- (ContractTemplate("","") +: state.state.contractTemplateSelection.contractTemplates.toList.toSeq)) yield {
            'option (
              'value /= c.identifier,
              c.name
            )
          }

If I select a value then I go to another page and then come back to this page the same select value is still selected.

What I would like is that the select value defaults back to the first empty one.

Currently I have to force it to select the first one

    access.property(mySelected).set('value, "")

**Comment by fomkin** [comment]
This is expected behavior. Korolev doesn't recreate nodes. It is a reason why forms hasn't resets on state update. You solution completely legal.
