### ISSUE TITLE
adding prefix to html tag to include meta tag

### ISSUE THREAD

**Issue by undetail** [fomkin/korolev#220]
Hello

First Korolev is a really helpful project. 
Is it possible to modify the html tag in order to include prefix argument? (open graph)

Kind regards

**Comment by fomkin** [comment]
Hi! You mean XML namespaces? Well, HTML doesn't support them on syntax level. I mean `<og:tag>` is not valid HTML syntax. Browsers interpreting some tags as tags from different namespaces. For example if you write `<svg>` tag it will be created in `http://www.w3.org/2000/svg` namespace. Also DOM model supports namespaces, and when you creating DOM element dynamically, you need to specify namespace explicitly.

Korolev supports dynamic namespaces (see example https://github.com/fomkin/korolev/blob/v0.8.0/examples/game-of-life/src/main/scala/GameOfLife.scala#L39) but there is no way to create prefix in static HTML. As I know best practice for custom tags to specify namespaces this way: `<ok-mytag>`.  In Korolev template it will be `'okMytag`.

Returning to open graph. Why do you need namespace prefix? as I know open graph definitions uses meta tags in head section. Something like `<meta property="og:type" content="article" />`.

**Comment by undetail** [comment]
Hi. 

I am really new in the area of html, dom and in general web programming. I was thinking that in order to make open graph tags working, someone has to indicate the prefix in the html tag. My intend is to used Korolev for a dynamic website (analytics from an old excel + plugin + scala to a pure scala ... for that purpose Korolev is excellent). As I see also with namespace, someone could replace theoretically (server charge) replaced some javascript code,

**Comment by fomkin** [comment]
First of all we need to ensure that we are talking about same things. When I say "Open Graph" I mean this https://developers.facebook.com/docs/sharing/webmasters?locale=en_US

**Comment by undetail** [comment]
yes we are talking about the same things. It is cosmetic.

**Comment by undetail** [comment]
Yes it was this that I mean.

I jump on another sunject. When I integrate canvas tag with javascript code (chartjs), any modification of the javascript code is not taken into account. I have try to integrate a an id, a fake css classes in order to trigger the change. It looks like modifications are not sent to the client. (modification on others tag are sent). For example I would like to have a radio area where users can change the time window of chart.   

Again I am not fully in web programming so I could have miss some points.

**Comment by fomkin** [comment]
> I jump on another sunject. When I integrate canvas tag with javascript code (chartjs), any modification of the javascript code is not taken into account. I have try to integrate a an id, a fake css classes in order to trigger the change. It looks like modifications are not sent to the client. 

I've answered in Gitter about JS https://gitter.im/fomkin/korolev. Also you can ask @solverit in Telegram messenger about charts in Korolev.
