### ISSUE TITLE
Dynamic <head>

### ISSUE THREAD

**Issue by fomkin** [fomkin/korolev#221]
Currently `<head>` is the same for all application. We can't modify it for different pages. What we need to do:

1. `KorolevServiceConfig(head = ...)` should be function.
2. Standard things like a `title`, `css` and `script` urls, should be able to get defined as strings.
3. Custom tags also should be supported. It's required for custom metadata.
4. `<head>` tag attributes should be customizable. It's also required for custom metadata (Facebook Open Graph for example).

```scala
head = { state =>
  Head(
    title = "Hello world",
    styles = Seq(...),
    scripts = Seq(...),
    customHeadAttributes = Map()
    customTags = Seq(
      'meta(...)
    )
  )
}
```

**Comment by s0kil** [comment]
Is there any progress on this issue?

**Comment by greenhost87** [comment]
@s0kil Already done with https://github.com/fomkin/korolev/commit/cad1152596d0425b74f4d0546c156aca08eb1d12

**Comment by fomkin** [comment]
@greenhost87 Just noticed your comment. @s0kil Actually it is not true. The mentioned commend is about passing state at static page rendering phase.

**Comment by fomkin** [comment]
```scala
document = Html(
  head(...),
  body(...)
)
```
