### ISSUE TITLE
XML-literals DSL

### ISSUE THREAD

**Issue by fomkin** [fomkin/korolev#24]

**Comment by olafurpg** [comment]
FWIW, in monadic-html we have a Scala.js compatible version of scala-xml implemented in 200 LOC with some additional type-safety for what can be embedded in element or attribute position. See https://github.com/OlivierBlanvillain/monadic-html/blob/master/monadic-html/src/main/scala/scala/xml/xml.scala

If you drop the type-safety features, it's ~100 LOC.

Note. This does not include an xml pretty printer.

**Comment by fomkin** [comment]
@olafurpg wow, looking great. Do you have a plan to publish your `scala.xml` implementation as single artifact both for scala.jvm and scala.js?

**Comment by olafurpg** [comment]
I don't think we'll publish it as a standalone library for jvm+js, it's at least outside the scope of monadic-html.

It should be trivial to move it to a separate repo however and publish for jvm + js. It's a single file, MIT licenced. The only shame is that it occupies the `scala.xml` global namespace. You'd have to remove the mhtml specific typeclass instances for Xml{Element,Attribute}Embeddable. We keep the instances on the companion objects to avoid forcing an import on users.

**Comment by fomkin** [comment]
👍

**Comment by olafurpg** [comment]
We can discuss later about consolidating implementations if namespace conflicts end up being a problem.

**Comment by fomkin** [comment]
Out of scope of Korolev. Moved to https://github.com/fomkin/levsha

**Comment by fomkin** [comment]
https://github.com/fomkin/levsha/issues/1
