### ISSUE TITLE
Compress Only In Production

### ISSUE THREAD

**Issue by s0kil** [fomkin/korolev#297]
The `korolev-client.min.js` run-time should only be minified in a production build, this will provide transparency for newcomers like me to understand how the run-time works, and also aid in easier debugging.

Also, in prod the `korolev-client.min.js` could be be compressed with `gzip` and `brotli` for even smaller bundles. I have tested both and results are, with `gzip` run-time is `3.3kB` and with brotli `2.8kB`

**Comment by fomkin** [comment]
> The korolev-client.min.js run-time should only be minified in a production build

Is source map not enough?

> Also, in prod the korolev-client.min.js could be be compressed with gzip and brotli for even smaller bundles.

Good idea!

**Comment by s0kil** [comment]
Source map is enough, Все круто

**Comment by s0kil** [comment]
Note: Not only can we compress JavaScript with `brotli` & `gzip`, But also the Initial HTML response, and each WebSocket Response.

> A naive implementation will simply compress all message payloads, whereas a smart server may offer an additional API to indicate which payloads should be compressed.

Ref: https://www.igvita.com/2013/11/27/configuring-and-optimizing-websocket-compression/

**Comment by fomkin** [comment]
I thought a little about compression. Korolev application is an Akka route. I guess that it's possible to wrap it with [encodeResponse](https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/coding-directives/encodeResponse.html) directive. Also in my practice most of Korolev applications stands before Nginx. It's possible to apply compression on this stage.
