### ISSUE TITLE
Timers: way to schedule transitions

### ISSUE THREAD

**Issue by fomkin** [fomkin/korolev#30]
It may be useful when we want to play some basic animation or hide something after timeout.

Global timer (session context)
```scala
KorolevServer[Boolean](
  ...
  timers = {
    case true => 
      delay(2 seconds) {
         case _ => false
      }
  }
)
```
Inside view
```scala
render = {
  case state =>
    'div(
      h1("Title"),
      if (!state) <> 
      else 'div(
        "Something we want to hide",
        delay(2 seconds) {
          case _ => false
        }
      )
    )
}
```

**Comment by vsuharnikov** [comment]
It looks like that the `delay` it is not a part of a view. We could incapsulate the flag in a state, and change it in 2 seconds. Something like:
```scala
case class AppState(flashVisible: Boolean = false, …)

render = {
  case state =>
    'div(
      h1("Title"),
      if (state.flashVisible) Some('div("Something we want to hide")) else None
    )
}

// Change the flashVisible
// …
```

What do you think?

**Comment by fomkin** [comment]
@vsuharnikov 

> It looks like that the delay it is not a part of a view.

It's may part of view behavior, like CSS animation. For example we show some notification an hide it after delay. It reasonable to make it as part of view. Delay is an effect which produce transition that changes a state.
