### ISSUE TITLE
Remove StateStorage, StateSerializer, StateDeserializer 

### ISSUE THREAD

**Issue by fomkin** [fomkin/korolev#302]
We decided to move `StateStorage` under the hood. Saving state to external storage demanded by no one.

**Comment by greenhost87** [comment]
But what about using something like Memcached for session storage when you need move you application to cluster with high load or you think that clustering not need on Korolev level and must be solved by something like Nginx or HAProxy?

**Comment by fomkin** [comment]
@greenhost87 you can use consistent hashing to ensure that all requests from the user processed by only one node.

**Comment by Zhen-hao** [comment]
I think `StateStorage` might be useful to do rolling updates/releases without causing users to lose the current pages.
