### ISSUE TITLE
Replace DIV with Button automatic fire click event

### ISSUE THREAD

**Issue by greenhost87** [fomkin/korolev#317]
In new 0.15.0 release new bug was introduced. 

Information - we have simple page element and want to show\hide it via button click, if we replace div with simple `button` for some reason `click` event fired two times and as result after two state mutation we still have our element not hidden.
Simple way to 'fix' problem is put `button` inside `div` but I think problem can be more complex.

Minimal example code for reproduce bug:

```scala
import korolev.Context
import korolev.akka.{AkkaHttpService, SimpleAkkaHttpKorolevApp, akkaHttpService}
import korolev.server.{KorolevServiceConfig, StateLoader}
import korolev.state.javaSerialization._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.Future

object ReproduceApp extends SimpleAkkaHttpKorolevApp {

  import State.globalContext._
  import levsha.dsl._
  import html._

  val service: AkkaHttpService = akkaHttpService {
    KorolevServiceConfig[Future, Boolean, Any](
      stateLoader = StateLoader.default(true),
      render = { state =>
        body(
          s"State is $state",
          if (state) {
            div(
              "look like filter",
              button(
                "Hide",
                event("click") { access =>
                  access.maybeTransition {
                    case t =>
                      !t
                  }
                }
              )
            )
          } else {
            // TODO: Uncomment to "fix"
//            div(
            button(
              "Show",
              event("click") { access =>
                access.maybeTransition {
                  case t =>
                    !t
                }

              }
            )
//            )
          }
        )
      }
    )
  }
}

object State {
  val globalContext = Context[Future, Boolean, Any]
}
```

**Comment by greenhost87** [comment]
Additional information, problem caused because of concurrency. Base on example code let's see what happened:
* user click button on UI, for Korolev this button have id `1_2_2`
* server start process event with `ApplicationInstance.onEvent` for processing it generates list of events

```
0 = {events$EventId@7154} "EventId(1,click,Capturing)"
1 = {events$EventId@7155} "EventId(1_2,click,Capturing)"
2 = {events$EventId@7156} "EventId(1_2_2,click,AtTarget)"
3 = {events$EventId@7157} "EventId(1_2_2,click,Bubbling)"
4 = {events$EventId@7158} "EventId(1_2,click,Bubbling)"
5 = {events$EventId@7159} "EventId(1,click,Bubbling)"
```

When event 3 proceed via `topLevelComponentInstance.applyEvent(eventId)` we got DOM mutation and new DOM and `events` collection contains new event `click` for element `1_2` which is our new button. But code inside `ApplicationInstance.onEvent` continue do `forall` and on next iteration apply event `4` -> `EventId(1_2,click,Bubbling)` and this trigger our fresh new button and that perform second transition, back to state of application before user click UI.

**Comment by fomkin** [comment]
Korolev 0.15.0 has a bug fix. It solves stopping event propagation by default. Now it can be controlled by `stopPropagation` flag https://github.com/fomkin/korolev/commit/9aec507873ea0fa40a401bf41611e3fd3e6b8313. The situation you described happend because of asyncronous nature of event processing and transitions in Korolev.
