### ISSUE TITLE
abstract class StateManager shouldn't require StateDeserializer and StateSerializer

### ISSUE THREAD

**Issue by Zhen-hao** [fomkin/korolev#338]
this is a refactoring proposal. I can open a PR after we agree on the approach

`StateSerializer` and `StateDeserializer` are used only in the default state manager's dev mode. 

We should remove these requirements from the method signatures inside `StateManager[F[_]: Effect]`, as those should be implementation details of `read` and `write`. 

This would also give users an opportunity to bring in their own serialization mechanism, for example, with Avro and a Schema registry.

**Comment by Zhen-hao** [comment]
As an example, I used a distributed mem cache via Akka distributed data (d-data) in my project. You can see the `InMemoryStateManager` doesn't need to serialize or deserialize. we do need to have a serializer and deserializer for d-data, but it is handled by adding an Akka serializer.
You can see the usage of a distributed cache as an implementation detail in my `InMemoryStateManager`. 
I think we can decouple serialization from the state manager, we might be able to treat dev-mode as a plugin (discoverable at runtime) and allow users to add dev-mode to their own stage storage. 

@fomkin what do you think?

```scala
class AvroUiStateStorage(implicit val system: ActorSystem) extends StateStorage[Future, UiState] {

  import scala.concurrent.ExecutionContext.Implicits.global

  implicit val akkaScheduler = system.scheduler.toTyped
  implicit val distributedCache = system.spawn(DistributedUiStateCache(), safe"ui-states")

  implicit val timeout: Timeout = 3.seconds
  private val cache = TrieMap.empty[String, StateManager[Future]]

  def mkKey(deviceId: DeviceId, sessionId: SessionId): String = {
    s"$deviceId-$sessionId"
  }

  def getStatesForKey(key: String): Future[Option[StateManager[Future]]] =
    distributedCache.ask(ref => DistributedUiStateCache.GetStatesForSession(ref, key)).map {
      case DistributedUiStateCache.UiStates(states) =>
        if (states.isEmpty)
          None
        else {
          val sm = InMemoryStateManager(key, states)
          cache.put(key, sm)
          Some(sm)
        }
    }

  /**
    * Check if state manager for the session is exist
    */
  def exists(deviceId: DeviceId, sessionId: SessionId): Future[Boolean] = {
    val key = mkKey(deviceId, sessionId)

    if (cache.contains(key))
      Future.successful(true)
    else getStatesForKey(key).map(_.nonEmpty)

  }

  /**
    * Create new state manager
    */
  def create(deviceId: DeviceId, sessionId: SessionId, state: UiState): Future[StateManager[Future]] = {

    import KorolevSerializer._

    //TODO delete me
    println("Create new state manager")

    val key = mkKey(deviceId, sessionId)
    val sm = new InMemoryStateManager(key, distributedCache)
    cache.put(key, sm)
    Effect[Future].map(sm.write(Id.TopLevel, state))(_ => sm)

  }

  /**
    * Restore session manager from storage
    */
  def get(deviceId: DeviceId, sessionId: SessionId): Future[StateManager[Future]] = {

    //TODO delete me
    println("Restore session manager from storage")

    def errored =
      Effect[Future]
        .fail[StateManager[Future]](new NoSuchElementException(s"There is no state for $deviceId/$sessionId"))
    val key = mkKey(deviceId, sessionId)
    cache.get(key) match {
      case None =>
        getStatesForKey(key).flatMap {
          case Some(sm) =>
            Effect[Future].delay(sm)
          case None =>
            errored
        }
      case Some(sm) => Effect[Future].delay(sm)
    }
  }

  /**
    * Marks session to remove
    */
  override def remove(deviceId: DeviceId, sessionId: SessionId): Unit = {
    val key = mkKey(deviceId, sessionId)
    cache.remove(key)
    distributedCache ! DistributedUiStateCache.RemoveAllStates(key)
  }
}

class InMemoryStateManager(key: String, distributedCache: ActorRef[DistributedUiStateCache.Command])
    extends StateManager[Future] {

  val cache: TrieMap[Id, Any] = TrieMap.empty[Id, Any]

  val snapshot: Future[StateManager.Snapshot] = Effect[Future].pure {
    new StateManager.Snapshot {
      def apply[T: StateDeserializer](nodeId: Id): Option[T] =
        try {
          cache.get(nodeId).asInstanceOf[Option[T]]
        } catch {
          case _: ClassCastException =>
            None
        }
    }
  }

  def read[T: StateDeserializer](nodeId: Id): Future[Option[T]] =
    Effect[Future].map(snapshot)(_.apply(nodeId))

  def delete(nodeId: Id): Future[Unit] =
    Effect[Future].delay {
      cache.remove(nodeId)
      distributedCache ! DistributedUiStateCache.RemoveState(key, nodeId)
      ()
    }

  def write[T: StateSerializer](nodeId: Id, value: T): Future[Unit] =
    Effect[Future].delay {
      cache.put(nodeId, value)
      value match {
        case s: UiState => distributedCache ! DistributedUiStateCache.UpdateState(key, nodeId, s)
      }
      ()
    }
}

object InMemoryStateManager {
  def apply(key: String, states: scala.collection.mutable.Map[Id, UiState])(implicit
      distributedCache: ActorRef[DistributedUiStateCache.Command]): InMemoryStateManager =
    new InMemoryStateManager(key, distributedCache) {
      override val cache: TrieMap[Id, Any] = TrieMap.from(states)
    }
}
```

**Comment by fomkin** [comment]
Does Avro use runtime reflection to serialize the data?

**Comment by Zhen-hao** [comment]
> I use `obj.getClass().getName()` to get the right encoder/decoder from a lookup table (a `Map`). so the runtime reflection is minimal.

actually, this doesn't need reflection. see https://stackoverflow.com/a/7398133/5366961

**Comment by fomkin** [comment]
> I use obj.getClass().getName() to get the right encoder/decoder from a lookup table (a Map). so the runtime reflection is minimal.

`StateSerializer` and `StateDeserializer` are required to do same thing in _compile time_,

**Comment by Zhen-hao** [comment]
@fomkin your default implementation doesn't use the serializer or the deserializer except for in the dev mode.  I think the abstract class shouldn't be concerned with serialization. 

Now I have to do this in my project to make the compiler happy. 
```scala
implicit def UiStateSerializer[T <: KorolevSerialization]: StateSerializer[T] =
    new StateSerializer[T] {
      def serialize(value: T): Array[Byte] = {
        // this will never run
        ???
      }
    }
```

**Comment by fomkin** [comment]
You right. Korolev uses serialization nowhere exept dev mode. But imagine that someone want to make StateStorage, which saves data as JSON using [Circe](https://circe.github.io/circe/). Of course he or she can resolve codecs by runtime mapping, as you do. But I regard it as hack, and I sure many of Scala devepers will agree with me. I had [thoughts](https://github.com/fomkin/korolev/issues/302) to move StateStorage under the hood, because customization of this was not demanded by anyone. But you apears and says that you will use it. So I decided to let it be as it is.

**Comment by Zhen-hao** [comment]
if you think it will make it better, I can take some time to refactor it. 
otherwise, we can leave it as it is.
