### ISSUE TITLE
state transition from emptyList to nonEmpty list not working

### ISSUE THREAD

**Issue by ranglang** [fomkin/korolev#342]
i hava a feed list,  i has some feed, it works find 
than i change query condition, i become empty now , it works find now.
however, i change query condition again, i become nonEmpty now, but browser not receiving any Js code

**Comment by ranglang** [comment]
i will show a demo later if it's needed

**Comment by fomkin** [comment]
Case you described should be covered. It will be nice, if you will provide demo.
