### ISSUE TITLE
a component cannot be put inside a form

### ISSUE THREAD

**Issue by Zhen-hao** [fomkin/korolev#352]
this can cause unexpected behaviors without clear logs. 
is it because event emitting from components only works in `div` and not `form`?

**Comment by fomkin** [comment]
May you provide example to reproduce the problem?

**Comment by Zhen-hao** [comment]
will do it later when I find more time.
because a component is heavy to setup...

BTW, do you have a project template for bug reporting? it would make it much easier

**Comment by greenhost87** [comment]
Is this still actual?

**Comment by Zhen-hao** [comment]
you can close this one. 
I didn't get time to try it. 
I also realized that my way of using components isn't the way it was designed for.
I always create components inside the render function. @fomkin said I shouldn't do it. I want to refactor my code a bit later.
