### ISSUE TITLE
protocol description link is broken

### ISSUE THREAD

**Issue by Zhen-hao** [fomkin/korolev#367]
This [linked page](https://github.com/fomkin/korolev/blob/v0.17.0/korolev/src/main/protocol.md) in https://github.com/fomkin/korolev/blob/master/docs/user-guide.adoc#71-debug-mode
leads to 404

**Comment by fomkin** [comment]
https://github.com/fomkin/korolev/commit/3342d9250f77c53d2d3eb068e897cf2ce7fb07a8
