### ISSUE TITLE
replacement of `delay`

### ISSUE THREAD

**Issue by Zhen-hao** [fomkin/korolev#385]
hi, I noticed that `delay` has been deprecated. 

However, I have some use cases where I have to use `delay`.

One scenario is as follows.

I tried to update the UI upon event returned by this component:

```scala
val timeComponent =
            myComponent(
              MyParam(myparamList)) {
              (access, event) =>
                event match {
                  case Valid(newProposal) =>
                    for {
                      _ <- newProposal match {
                        case Some(proposal) =>
                          for {
                            _ <-
                              access
                                .property(startInputId)
                                .set(
                                  "value",
                                  s"${proposal.startEpoch.toLocalTime().toString()}")
                            _ <- access.property(startInputProblem).set("value", "")
                            _ <- access.property(durationInputId).set("value", s"${proposal.durationInMinutes}")
                            _ <- access.property(durationInputProblem).set("value", "")
                          } yield ()
                        case _ => ().pure[Future]
                      }
                      _ <- access.transition(_ => state.copy(meetingProposal = newProposal))
                    } yield ()

                  case invalid @ Invalid(errors) =>
                    access.transition(_ => state.copy(errors = state.errors ++ errors.toList))

                }
            }
```
somehow this gives a runtime error that `startInputId` is not found.

My workaround is to use `delay` in the rendering:

```scala
if (proposal.nonEmpty) delay(0.01.seconds) { access =>
                for {
                  _ <-
                    access
                      .property(startInputId)
                      .set(
                        "value",
                        s"${proposal.get.startEpoch.toLocalTime().toString()}")
                  _ <- access.property(startInputProblem).set("value", "")
                  _ <- access.property(durationInputId).set("value", s"${proposal.get.durationInMinutes}")
                  _ <- access.property(durationInputProblem).set("value", "")
                } yield ()
              }
```
which works.

**Comment by fomkin** [comment]
Currently `delay` is a way for dirty hacks. Looks like the situation is consequence of a bug (maybe this https://github.com/fomkin/korolev/issues/370). Possibility of such workarounds, pulls down priority of true problems.

**Comment by Zhen-hao** [comment]
I agree using `delay` is a hack. I hope the event-driven approach will work soon.

**Comment by Zhen-hao** [comment]
another use case of `delay` for me is "progressive page loading".
a state first renders a very minimal page and uses `delay` to fetch other stuff from the backend.

**Comment by Zhen-hao** [comment]
> another use case of `delay` for me is "progressive page loading".
> a state first renders a very minimal page and uses `delay` to fetch other stuff from the backend.

The downside of this pattern is that when `access.maybeTransition` is called,
`delay` will run again even if the state doesn't occur in the partial function passed to `maybeTransition`.

Another approach is to always follow transitioning into the state with a `publish` of an event that triggers backend communications. But it is tedious to do it every time you want to go to the state, and it is easy to forget.

**Comment by Zhen-hao** [comment]
> Another approach is to always follow transitioning into the state with a `publish` of an event that triggers backend communications. But it is tedious to do it every time you want to go to the state, and it is easy to forget.

After thinking about it for a while, this is still better than using `delay`.
