### ISSUE TITLE
Event Listeners stopped working 

### ISSUE THREAD

**Issue by gregor-i** [fomkin/korolev#394]
Hi,

today I checked out korolev and came across 2 strange situations. I assume they are bugs. I've constructed minimal examples for both cases from the examples of this repo.

1. If the DOM contains 2 adjacent text nodes, the following event listerners will stop working. See: https://github.com/gregor-i/korolev/commit/0b9056707c481f6ec6b1abff2290bc4c1b1b671e
2. If the DOM is wrapped in a table, (some?) event listeners will also not work. The event listener on the checkbox will work, but not the `dbclick` event listener. See: https://github.com/gregor-i/korolev/commit/6de874246fa049dff38cfaed7d30c1930f17d7cc

I'm assuming, the issue lies with the constructed ids (ie `0:1_2_2_1_8_2_1:dblclick`).

**Comment by greenhost87** [comment]
Some result of investigations.

Case 1:

We have situation in code you have "two" nodes and then you have button with event listener:

```
            "some text",
            "some more text",
            div(button("clear all todos", event("click")(_.transition(_.copy(todos = Vector.empty)))))
```

But moder browser merge two string into on one line `"some textsome more text"` as a result your div in JS have different ID than on serverside

Case 2: 

Similar problem, you change code to `table(tr(td(), td()))` but browser change it to `<table><tbody>...</tbody></table>` added `tbody` on browser side broke synchronization between Server and Client DOM state

**Comment by gregor-i** [comment]
Ok, thanks for the investigation.

So it's a known limitation and the service-side structure must be exactly the same as the structure the browser has interpreted.
As all these situations are valid, I'd suggest to document these limitations.
For future development: the limitation could be overcome by generating ids on the server and using them client-side. So the ids don't depend on browser-side optimizations.

There is probably also a 3rd case: If a text node is empty, the browser will omit the textNode. ie: 
```div("", span(event("click")(...))```
