### ISSUE TITLE
silent failure in nested access pattern

### ISSUE THREAD

**Issue by Zhen-hao** [fomkin/korolev#399]
I've seen issues in code like the following.

```scala
 for {
        state <- access.state
        _ <- state match {
          case State1 =>
            access.transition(_ => State2)
          case State2:  =>
            access.publish(MyEvent)
          case _ =>
             {println("in other states")}.pure[Future]
        }
} yield ()
```
The problem is that no effect is actually run. There are no errors in the logs.

**Comment by fomkin** [comment]
Are you sure that the event was handled? I do not see any problems in this code (except pure effect).

**Comment by Zhen-hao** [comment]
I was sure because replacing the above with 
```
access.publish(MyWorkaroundEvent)
```
works.

I will test again with the new 1.0 version when I have time. the issue was found with `1.0.0-RC1` and `1.0.0-RC2`

**Comment by fomkin** [comment]
1.0 and RCs don't have differences in Future based apps.

1. Please add more debug information.
2. Also try to wrap match statement with curly braces. I remember that I was facing with such problem.
3. Ensure that effect defined outside `optimize {}` block. Since it rewrite code, it could break it.

```scala
 for {
        state <- access.state
        _ = println(s"state = $state")
        _ <- {
          state match {
            case State1 =>
              println(s"state 1 matched")
              access.transition(_ => State2)
            case State2:  =>
              println(s"state 2 matched")
              access.publish(MyEvent)
            case _ =>
               {println("in other states")}.pure[Future]
          }
       }
} yield ()
```

**Comment by Zhen-hao** [comment]
Ironically, the problem is caused by my debug logging. Sorry that I oversimplified my code when creating the this bug.

I have the code in an Akka actor inside an extension.

My code was like 

```scala
 for {
        state <- access.state
        _ <- state match {
          case State1 =>
            context.log.debug("in state State1")
            access.transition(_ => State2)
          case State2:  =>
            context.log.debug("in state State2")
            access.publish(MyEvent)
          case _ =>
             {println("in other states")}.pure[Future]
        }
} yield ()
```
where `context` is the actor context. Removing the logging lines makes the code to work.

So, it could be a bug in Akka or in its integration in Korolev. I'm not sure which is the case.

But I now learned not to access the Actor context inside an `access.state` match block.
