### ISSUE TITLE
Performance benchmarks

### ISSUE THREAD

**Issue by fomkin** [fomkin/korolev#40]
Depend on #37 #25

**Comment by Fly-Style** [comment]
I just have started make a simple performance tests, using [Confess.js](https://github.com/jamesgpearce/confess) and [YSlow](http://yslow.org/) which are running by [PhantomJS](http://www.phantomjs.org/). 
Now I need you to approve these tools, and discuss the concrete benchmarks.

**Comment by fomkin** [comment]
@Fly-Style these tools about estimation of the quality of page. Not about testing server performance. It's suitable for regression testing of large code base in the projects. In our case we should count speed of server answers on a high load.

I suppose testing scenario should be like that:

1. We have to deploy an app wich has enough complexity to the target server.
2. The app already contains a js which can emulate user behavior. It counts the latency on each interaction. Finally it sends all collected metrics to phntomjs [callback](http://phantomjs.org/api/webpage/handler/on-callback.html). You can take any framework from [this list](http://phantomjs.org/headless-testing.html) but I not sure they they are suitable for our case because of Korolev asynchronous nature.
3. PhantomJS script opens 1000 instances of the page and waits for client metrics. Then report received, phantom closes page and append report to a CSV file.
4. Some script takes CVSs, makes aggregation, and generates pretty HTML with charts and tables.

**Comment by fomkin** [comment]
## Proposal (Draft)

Korolev needs performance benchmarks to track regressions. Performance benchmarks should be run manually after the new feature is merged to `develop` branch.

### Solution

We will use HTTP/WebSocket client to connect to `korolev-server`. After WebSocket connection is established test should emulate client behavior during initialization. When it should send user events (clicks) and track server reaction time. Metrics to collect:

1. Min reaction time
2. Max reaction time
3. Median reaction time

**Comment by fomkin** [comment]
Current implementation is slow.
