### ISSUE TITLE
add toIterator method to Stream

### ISSUE THREAD

**Issue by Zhen-hao** [fomkin/korolev#414]
I have a use case where I need to pipe the result of `access.downloadFilesAsStream` to Akka Stream. 
The easiest way is to convert the korolev stream to an instance of Scala Iterator. 

I now use the following code. but shouldn't it be part of the `Stream` class? 

```scala
  def toIterator[F[_]: Effect, B]: Stream[F, B] => F[Iterator[B]] = { stream =>
    Effect[F].delay(new Iterator[B] {

      var nextValue: B = ???
      def hasNext: Boolean =
        Effect[F].run(stream.pull()) match {
          case Left(ex) => throw ex
          case Right(Some(b)) =>
            nextValue = b
            true
          case Right(None) =>
            false
        }
      def next(): B = nextValue
    })
  }
```

Of course, I can do `stream.to(toIterator)` but it's a bit ugly.

PS.
my use case is to create an Akka Stream Source like
```scala
val source = Source.fromIterator(() => iter.map(b => ByteString(b.asArray)))
```

**Comment by fomkin** [comment]
The approach you offer is blocking. There is no way to implement `hasNext` and `nextValue` without `Await.result` or sort of. This is a bad practice in Scala. Korolev has integration with Akka Stream and Reactive Streams . See https://fomkin.org/korolev/user-guide.html#_streams.

Also Korolev can convert Bytes to ByteString using `Bytes#to[T]` function instead of `ByteString(b.asArray)`. In fact `to` in the case is just unboxing, because Bytes is a wrapper around ByteString (if you use Akka as http backend).

```scala
import korolev.akka.instances._

for {
  ...
  bytesStream <- access.downloadFileAsStream(fileHandler)
  akkaBytesSource = bytesStream.asAkkaSource
  akkaByteStringSource = akkaBytesSource.map(_.as[ByteString])
  ...
} yield ()
```

**Comment by Zhen-hao** [comment]
You are right about blocking. I didn't know you already had Akka integration, which is much better than my workaround. 

I wanted to understand your implementation of the reactivestreams interface but found the code not very clear. It seems that it heavily relies on the `Countdown` class. It would be great if you could add some documentation/comments to its file.

**Comment by Zhen-hao** [comment]
another low-hanging fruit would be to link to `6.6. Streams` from `2.10. File streaming` on the documentation page.

**Comment by fomkin** [comment]
> another low-hanging fruit would be to link to 6.6. Streams from 2.10. File streaming on the documentation page.
The project is open for PRs :)

**Comment by fomkin** [comment]
> I wanted to understand your implementation of the reactivestreams interface but found the code not very clear.

@Zhen-hao 
See https://github.com/reactive-streams/reactive-streams-jvm/tree/v1.0.3
`Publisher` gives `Subscription` to `Subscriber` via `onSubscribe` invocation. Now subscriber may `Subscription::request` for `n` items from publisher. As you may know, Korolev Stream is pull-based and you can pull items one-by-one. So we need mechanism which will pull items from Stream `n` times. Reactive Streams API allows to call `Subscription::request` within pulling process. It means the `n` can be changed dynamically. `Countdown` is very simple solution of this problem. On request it increments `n` inside itself. Then in the pulling loop it gives async lock if `n` become zero.

**Comment by Zhen-hao** [comment]
@fomkin thank you for your explaination!
I guess my difficulty is in understanding `def promise[A](cb: (Either[Throwable, A] => Unit) => Unit): F[A]`, which seems to be unique to korolev. I can't understand how `pending: Option[Effect.Promise[Unit]]` in `Countdown.State` can behave like a lock.

**Comment by fomkin** [comment]
@Zhen-hao See https://typelevel.org/cats-effect/docs/typeclasses/async. Korolev's `promise` has similar interface. `decOrLock` checks if `n` is 0 then saves callback to `pending`. The effect returned by `decOrLock` will be not finished until callback not invoked. `add` checks if `pending` contains saved callback then invoke it.

**Comment by fomkin** [comment]
There are a lot places where I use this technique https://github.com/fomkin/korolev/search?q=Promise

**Comment by Zhen-hao** [comment]
@fomkin thanks a lot for the pointers! 
To me personally, the name "lock" is really confusing because its real semantics is "(asynchronously) suspend running the callback by saving the callback in a state". Maybe you meant a lock on the callback. But locks have owners and owners have to release the locks. In the Korolev case, the lock was not released by the "owners". 

I can understand why you want to call it `promise` instead of `async`, seeing the return type `F[A]` instead of `F[Unit]`. 

Another "complain" I have is about the naming convention of callback in the Scala community. I prefer the name `continuation`. I think the name callback comes from languages that support callbacks on the language level with implementations that use pointers to functions. In Scala, the "callback" is just another pure data argument to the function being called.
