### ISSUE TITLE
File download streaming does not work using ZIO Http

### ISSUE THREAD

**Issue by Marc-Ducret** [fomkin/korolev#427]
To trigger the download, I used:
```scala
access.downloadFileAsStream(fileHandle)
```

Through debugging, I figured out the server receives the following HTTP request:
```
Method=POST
Route=/bridge/kMFnxwdNfvTbszuQSVWZUDNvpWvs8eXuxuAG4Jd3axaOkbRHc8aATF7BXW6MoS7g/k9BlBcpcwIiTuIwlrREInHvYBq3DNAIqayRZjqTGyTITfF88dpmkmK5x2wpGAAdV/file/1
```
with the body being a byte-array containing the whole (10MB) file at once.

I would expect instead to have a stream of smaller chunks of data so that the server can progressively consume the data without storing it all in RAM.

It might be a rather low level constraint of ZIO Http. Any idea about how to workaround this issue?

**Comment by fomkin** [comment]
As I understand, you received the body, but it consists of one chunk.

> with the body being a byte-array containing the whole (10MB) file at once.

There is no "at once" in networks. Chunk size in this case depends on network and buffer in HTTP backend. Most likely you run server on localhost and the file fits buffer in zio-http. Try to download bigger file, 1G for example. Also try to run code on remote server: hardware on the route to the server may slice TCP packets unpredictably.

**Comment by Marc-Ducret** [comment]
> As I understand, you received the body, but it consists of one chunk.

Yes, exactly.

As far as I understand, the place were the `HttpData` is constructed is here: https://github.com/dream11/zio-http/blob/8467a6aab35760ea85353aaac158bb5bb8c41354/zio-http/src/main/scala/zhttp/service/DecodeJRequest.scala#L16
Therefore it will always be of type `HttpData.CompleteData` and never `HttpData.StreamData`.
I don't think changing network conditions will have any effect.

I tested a 900 MB file which also ended up in one chunk; and 900 MB is enough to risk running out of memory on the server.

**Comment by fomkin** [comment]
So, looks like it is a problem of zio-http. I recommend to use Akka-http backend. It is fast and well tested. And it's compatible with ZIO in Korolev.

**Comment by fomkin** [comment]
Please notify  me when you will try akka-http. If it's OK, I will close the issue.

**Comment by Marc-Ducret** [comment]
I think we might stick with zio-http even though it seems incompatible with file streaming. It is not clear yet whether we will face memory issues or not and we are trying to avoid the akka dependency.

Also it seems that zio-http is getting a lot of updates, and there is this issue that seems relevant https://github.com/dream11/zio-http/issues/503. Therefore we still hope this will get solved with zio-http at some point.
