### ISSUE TITLE
ZioHttpExample issue

### ISSUE THREAD

**Issue by gkfabs** [fomkin/korolev#445]
Hello,

I was running `sbt 'zioHttpExample/run'` directly from command line with the tag v1.5.0

After connecting to `http://127.0.0.1:8088/` I see the `Push button`. When clicking on it, nothing happens. I was expecting `Push the button 1`

I think the root cause comes from ZioHttpKorolev. But I was unable to spot the exact problem.

Thanks

**Comment by gkfabs** [comment]
It looks like the problem comes from this commit https://github.com/fomkin/korolev/commit/35da0fae0b3c794884734f20201429e20598aa10

**Comment by fomkin** [comment]
Unfortunately I don't have a time to support this. After 1.6 zhttp and http4s interop will removed from this repository. Original author of zhttp interop is @morozov11, maybe he could help.
