### ISSUE TITLE
JRebel/DCEVM integration

### ISSUE THREAD

**Issue by fomkin** [fomkin/korolev#64]

**Comment by PhilAndrew** [comment]
DCEVM works, I have a DOS batch file like this:

set JAVA_OPTS=-javaagent:hotswap-agent-1.1.0-SNAPSHOT.jar=autoHotswap=true,extraClasspath=".\target\scala-2.11\classes"
sbt "run-main jumpmicro.jmcloner.impl.webserver.RunWebServer"

That runs my main class RunWebServer. Then I have it sbt ~compile as well.

The save then reload takes about 5-8 seconds on my machine, compile and reload.

**Comment by PhilAndrew** [comment]
It would be nice if somehow just that part of the Korolev code which I write to make the UI was interpreted, there must be some Scala interpreter at runtime as the UI code is likely to be changed frequently in a change/test/change/test cycle.. just google searching

https://gist.github.com/takawitter/5479445
https://gist.github.com/metasim/7492509
https://github.com/kostaskougios/scalascriptengine
https://groups.google.com/forum/#!topic/scala-user/k4P7lsSv9Dw

**Comment by fomkin** [comment]
@PhilAndrew 

> `\target\scala-2.11\classes`

Interesting! I tried to run DCEVM with 2.11 and it didn't work :)

> The save then reload takes about 5-8 seconds on my machine, compile and reload.

> It would be nice if somehow just that part of the Korolev code which I write to make the UI was interpreted, there must be some Scala interpreter at runtime as the UI code is likely to be changed frequently in a change/test/change/test cycle.. just google searching

I'm afraid it wont help. Scala "interpreter" uses regular Scala compiler. This approach will have the same speed as `~compile`.

**Comment by fomkin** [comment]
> It would be nice if somehow just that part of the Korolev code which I write to make the UI was interpreted, there must be some Scala interpreter at runtime as the UI code is likely to be changed frequently in a change/test/change/test cycle.. just google searching

But it awesome idea for side project.

**Comment by PhilAndrew** [comment]
This allows for change of Scala code and reload while the program keeps running, don't need to quit the program and re-start it.

So just to document the steps I did for DCEVM on Windows and be verbose. Refer to http://hotswapagent.org/.

1. I installed "Java 8 update 112, build 8" as this seems to be the version DCEVM likes.
http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html#jdk-8u112-oth-JPR
Also make sure Scala and SBT and Java all installed correctly and working.

2. Download "Java 8 update 112, build 8" and run the jar on windows by double clicking on it.
https://dcevm.github.io/
It will ask you to set the install directory so I selected the Java 8 ... whereever jdk1.8.0_112 is located ... then I press the "Replace by DCEVM" button.
Perhaps you can replace a later version of JDK, I'm not sure, I just use the version it says.

3. So, make sure this is the default Java your using by starting a Dos cmd prompt running "java -version"
It will say:

```
C:\Users\philip>java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Dynamic Code Evolution 64-Bit Server VM (build 25.71-b01-dcevmlight-8, mixed mode)

C:\Users\philip>
```

Note the Dynamic Code Evolution part about dcevm, that shows we have dcevm installed.

4. You need to get hotswap-agent-1.1.0-SNAPSHOT.jar and put it in the directory where you are running.
Refer to http://hotswapagent.org/ it links to its download there.

5. I create a run.bat

```
set JAVA_OPTS=-javaagent:hotswap-agent-1.1.0-SNAPSHOT.jar=autoHotswap=true,extraClasspath=".\target\scala-2.11\classes"
sbt "run-main jumpmicro.jmcloner.impl.webserver.RunWebServer"

```

6. I can run.bat and it runs my Korolov program.

7. In another Dos window I run sbt ~compile and it re-compiles every time source is changed.

So now there are two Dos windows, one is running the Korolov program and the other re-compiles every time the source changes. Now I can change some Scala code and after a few seconds it as re-compiled, then I go back to the page and refresh the page and it updates to match the Scala code change.

**Comment by fomkin** [comment]
https://github.com/fomkin/korolev/issues/123 delivers "hot reload" experience
