### ISSUE TITLE
Example did not run as according to docs

### ISSUE THREAD

**Issue by PhilAndrew** [fomkin/korolev#76]
Downloaded https://repo1.maven.org/maven2/com/lihaoyi/utest_2.11/0.4.4/utest_2.11-0.4.4.jar
[info] Compiling 1 Scala source to C:\home\projects\git\korolev\async\.jvm\target\scala-2.11\classes...
[info] Compiling 2 Scala sources to C:\home\projects\git\korolev\vdom\.jvm\target\scala-2.11\classes...
[info] Compiling 5 Scala sources to C:\home\projects\git\korolev\bridge\.jvm\target\scala-2.11\classes...
[info] Compiling 8 Scala sources to C:\home\projects\git\korolev\korolev\.jvm\target\scala-2.11\classes...
[info] Compiling 8 Scala sources to C:\home\projects\git\korolev\server\target\scala-2.11\classes...
[info] Compiling 6 Scala sources to C:\home\projects\git\korolev\server-blaze\target\scala-2.11\classes...
java.lang.RuntimeException: No main class detected.
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last simpleExample/compile:run for the full output.
[error] (simpleExample/compile:run) No main class detected.
[error] Total time: 28 s, completed Feb 18, 2017 10:53:34 AM

C:\home\projects\git\korolev>sbt simpleExample/run

**Comment by PhilAndrew** [comment]
Also, I like this very much, I've started using it in my MicroService library I am building which works in OSGi.

https://github.com/PhilAndrew/JumpMicro

SimpleExample works inside OSGi container Felix.
https://github.com/PhilAndrew/JumpMicro/blob/master/JMCloner/src/main/scala/jumpmicro/jmcloner/impl/actor/SimpleExample.scala

**Comment by Escapingbug** [comment]
Can't run on linux as well.

**Comment by fomkin** [comment]
Fixed in https://github.com/fomkin/korolev/commit/3b6e502e82b5f407c645e8a71eb0f82880ca6f88
