### ISSUE TITLE
Support static assets such as images, js, css

### ISSUE THREAD

**Issue by PhilAndrew** [fomkin/korolev#77]
When a http request comes in it goes through korolev/server/package.scala:

    def renderStatic(request: Request): F[Response] = {

If the file is a javascript static resource then it returns

    <!DOCTYPE html><html ><head ><script > then the javascript code -

resulting in a error

**Comment by fomkin** [comment]
If assets are placed in `static` directory within classpath they would be served. https://github.com/fomkin/korolev/tree/master/examples/routing/src/main/resources/static

**Comment by PhilAndrew** [comment]
Requirement is that it must be in the static folder. I tested javascript and css and it works. Thanks.
