### ISSUE TITLE
Please explain the things which are not obvious

### ISSUE THREAD

**Issue by PhilAndrew** [fomkin/korolev#98]
Hi! Could you please explain the following methods, what is the difference between them, or document them in code?

immediateTransition
deferredTransition
noTransition

event
eventWithAccess

**Comment by fomkin** [comment]
Hi!

> immediateTransition
> deferredTransition
> noTransition

This is a way to construct `EventResult`. 

1. `immediateTransition ` - Is a transition which be applied to current state right now. It's useful to making lightweight synchronous transitions. For example you have a page with the "Query" field and the "Search" button. When the button was clicked, your application requests database or micro-service to execute the query. But user want to see reaction be before you receive the data. So you update the state with "Loading" flag in `immediateTransition` and user see reaction immediately. Signature of `immediateTransition` is `Transition[S]` which are type alias to `PartialFunction[S, S]` where `S` is your state type.
2. `deferredTransition` - In previous example your application does request to some sort of backend. Such request in Scala usually is asynchronous. So `deferredTransition` is a way to make your application await for response. `deferredTransition` will be applied to the state when the `Future` will be completed. Signature of `deferredTransition` is `Future[Transition[S]]`.
3. `noTransition` - It mens you don't want to make any reaction.

> event
> eventWithAccess

1. `event` - Just event callback. In this callback your code can't retrieve information from the client. It useful when you want to make some sort of "Next" button.
2. `eventWithAccess` - Same as `event`, but gives your code access to the client. Use it when you want to read values from the fields.

**Comment by PhilAndrew** [comment]
I wish to list the files in a directory when the page is first loaded, how would you do an asynchronous process which loads the initial state? I notice the StateStorage.default[Future, State](State()) if I use a function here for loading the state then the page doesn't complete load until the function has completed.

How could I then do a function after the page has loaded, I thought of something like:

          event('load) {
            immediateTransition { case s =>

but didn't work :(

**Comment by fomkin** [comment]
The method that you are looking for will be added in 0.3.0. The release is planned on next week. For now you can copy it from here https://github.com/fomkin/korolev/blob/develop/server/src/main/scala/korolev/server/StateStorage.scala#L86

**Comment by PhilAndrew** [comment]
I'm not sure if what you said is true. Here the page didn't load for the first 5 seconds. I would like the page to load and then the user can still interact with it while the data is loaded in 5 seconds time.

  object MyStorage {
    def getStateByDeviceId(deviceId: StateStorage.DeviceId): Future[State] = Future {
      Thread.sleep(5000)
      State()
    }
  }
  val storage = StateStorage.forDeviceId[Future, State] { deviceId =>
    MyStorage.getStateByDeviceId(deviceId)
  }

**Comment by fomkin** [comment]
O, I see. This can help you https://github.com/ognick/wizards-of-portal/blob/master/server/src/main/scala/wop/server/WopServer.scala#L46

`envConfigurator` is a way to combine your app with some kind of envirinment. In the example it is a Akka actors.

**Comment by PhilAndrew** [comment]
How would you clear out a form when it is submitted? as the form is not bound to state.

https://github.com/fomkin/korolev/blob/develop/examples/simple/src/main/scala/SimpleExample.scala

When this occurs
eventWithAccess('submit) { access =>

Need an immediateTransition first where it can clear out the form?

**Comment by fomkin** [comment]
> How would you clear out a form when it is submitted? as the form is not bound to state.

Good question. Looks like there is no way to do it now. Inputs are stateful, and we need an effect to update state of input. It's simple task. I add this functionality before tomorrow release.

**Comment by PhilAndrew** [comment]
How about 
form validation? 
preventing form re-submission in a short time if user clicks button twice quickly?

**Comment by fomkin** [comment]
> preventing form re-submission in a short time if user clicks button twice quickly?

Set button disabled after first click with the `immediateTransition`.

**Comment by fomkin** [comment]
@PhilAndrew BTW could you add OSGi section to documentation (WIP)? https://github.com/fomkin/korolev/tree/issue-17

**Comment by PhilAndrew** [comment]
Yes I'll take a look at documenting that in the near future.
I was wondering, how would you make an infinite list of items like twitters feed of items? Infinite lists are often useful.

**Comment by fomkin** [comment]
> I was wondering, how would you make an infinite list of items like twitters feed of items? Infinite lists are often useful.

I think it is not Korolev's job. It may be web-component that able to emit the event that will trigger next chunk load (this be handled by Korolev).

**Comment by PhilAndrew** [comment]
How can Korolev communicate with the web component, say the web component needs to indicate it wants more data, a new page of data to display. How can the web component communicate to Korolev and Korolev also communicate back?

Secondly there would be two ways to send HTML to the web component, either via HTML added to the page or by JSON

**Comment by fomkin** [comment]
@PhilAndrew 

> How can Korolev communicate with the web component, say the web component needs to indicate it wants more data, a new page of data to display. How can the web component communicate to Korolev and Korolev also communicate back?

WebComponent should behave as a regular HTML tag. It can watch its children list and can dispatch events. Korolev can append new subelements and can handle events. It the case of infinite feed the feed component should dispatch "bottomReached"  when user has scrolled down to bottom. Then Korolev handle the event and set attribute "loading" to true as immediate transition. Component shows a loading animation. In deferred transition Korolev asks some backend about new data an then appends loaded chunk to component via appending new children elements.

```scala
'myComponent(
  'loading when state.loading,
  state.feed map { item =>
    'div(
      'div(s"Author: ${item.author}"),
      'div(s"Author: ${item.message}")
    )
  },
  'event('bottomReached) {
    immediateTransition { case s => s.copy(loading = true) }
    .deferredTransition {
      feedBackend.loadNext(...) map { chunk =>
        transition { case s => s.copy(feed = s.feed ++ chunk) }
      }
    }
  }
)
```

Also you can use `envConfigurator` to subscribe to some sort of queue and update user's feed dynamically without patching view layer.
